# Generated by Django 5.2 on 2025-04-19 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_memo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to=settings.AUTH_USER_MODEL),
        ),
    ]
